name: Generate ASCII artwork 

on: push

jobs:
  ascii_job:
    runs-on: ubuntu-latest  
    
    steps:
      - name: Checkout repo 
        uses: actions/checkout@v4
        
      - name: Install Cowsay Program  
        run: sudo apt-get install cowsay -y 

      - name: Execute Cowsay CMD 
        run: cowsay -f rabbit "run for ur life rawrrrrrrrrr" >> dragon.txt 

      - name: Test file exists 
        run: grep -i "." dragon.txt 

      - name: Read file 
        run: cat dragon.txt 
      
      - name: List repo Files
        run: ls -ltra

    #  - name: Read files  
    #    run: cat README.md
