name: Testing my code

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest  # Fixed "ubuntu_latest" to "ubuntu-latest"
    
    steps:
      - name: Checkout repo 
        uses: actions/checkout@v4
        
      - name: Welcome Message  # Fixed "Welcoem" typo
        run: echo "My First GitHub Actions job"

      - name: List files  # Fixed "-name" to "- name"
        run: 
          echo "My first Github Actions Job"
          ls -ltra
          cat README.md

      - name: Generate ASCII ARtwork 
        run: cowsay -f daragon "run for ur life" >> dragon.txt

    #  - name: Read files  # Fixed "-name" to "- name"
    #    run: cat README.md
